
services:

  redis:
    image: redis:7
    container_name: ddos-redis
    ports:
      - "6379:6379"
    networks:
      control-net:
        aliases:
          - ddos-redis
          - redis

  attacker:
    build: ./attacker
    container_name: ddos-attacker
    networks:
      - lab-net

  victim:
    build:
      context: .
      dockerfile: victim/Dockerfile
    container_name: ddos-victim
    depends_on:
      - redis
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      - lab-net
      - control-net
    hostname: victim
    environment:
      - REDIS_HOST=redis
      - CAPTURE_INTERFACE=eth0

networks:
  control-net:
    driver: bridge

  lab-net:
    driver: bridge
    internal: true
